INSERT INTO usuarios (nombre, apellido, email) VALUES ('Juan', 'Pérez', 'juan.perez@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Antonio', 'López', 'antonio.lopez@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Marta', 'Torres', 'marta.torres@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Alejandro', 'González', 'alejandro.gonzalez@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Gonzalo', 'Martínez', 'gonzalo.martinez@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Ernesto', 'Ruiz', 'ernesto.ruiz@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('María', 'Sánchez', 'maria.sanchez@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Gerard', 'Romero', 'gerard.romero@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Lucía', 'Blanco', 'lucia.blanco@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Eric', 'García', 'eric.garcia@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Jonatan', 'Gómez', 'jonatan.gomez@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Eugenia', 'Serrano', 'eugenia.serrano@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Paola', 'Del-Rio', 'paola.delrio@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Jose Javier', 'Peral', 'josejavier.peral@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Cintia', 'Parejo', 'cintia.parejo@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Raquel', 'Valle', 'raquel.valle@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Beñat', 'Iglesias', 'beñat.iglesias@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Luis', 'Pons', 'luis.pons@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Daniel', 'Gómez', 'daniel.gomez@example.com');
INSERT INTO usuarios (nombre, apellido, email) VALUES ('Sandra', 'García', 'sandra.garcia@example.com');
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('El Infierno', 'Carmen Mola', 2023 , 13);
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('La armadura de la luz', 'Ken Follett', 2023 , 18);
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('El problema final', 'Arturo Pérez-Reverte', 2023 , 28);
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('Holly', 'Stephen King', 2023 , 21);
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('Christine', 'Stephen King', 1983 , 15);
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('Los inocentes', 'María Oruña', 2023 , 12);
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('El hobbit', 'J.R.R. Tolkien', 1937 , 15);
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('Nada es verdad', 'Verónica Raimo', 2022 , 11);
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('La sombra de la rosa', 'Ángela Banzas', 2023 , 27);
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('Este dolor no es mío', 'Mark Wolynn', 2017 , 11);
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('El camino de los reyes(El Archivo de las Tormentas 1)', 'Brandon Sanderson', 2010 , 24);
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('Palabras radiantes(El Archivo de las Tormentas 2)', 'Brandon Sanderson', 2014 , 22);
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('Juramentada(El Archivo de las Tormentas 3)', 'Brandon Sanderson', 2017 , 21);
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('Invisible', 'Eloy Moreno', 2018 , 21);
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('Violeta', 'Isabel Allende', 2022 , 19);
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('Más allá del invierno', 'Isabel Allende', 2017 , 20);
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('Cien años de soledad', 'Gabriel García Márquez', 1967, 15);
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('1984', 'George Orwell', 1949, 10);
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('El Gran Gatsby', 'F. Scott Fitzgerald', 1925, 12);
INSERT INTO libros (nombre, autor, fecha, cantidad) VALUES ('Matar a un ruiseñor', 'Harper Lee', 1960, 18);
