INSERT INTO usuarios (id, nombre, apellido, email) VALUES (1, 'Juan', 'Pérez', 'juan.perez@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (2, 'Antonio', 'López', 'antonio.lopez@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (3, 'Marta', 'Torres', 'marta.torres@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (4, 'Alejandro', 'González', 'alejandro.gonzalez@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (5, 'Gonzalo', 'Martínez', 'gonzalo.martinez@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (6, 'Ernesto', 'Ruiz', 'ernesto.ruiz@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (7, 'María', 'Sánchez', 'maria.sanchez@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (8, 'Gerard', 'Romero', 'gerard.romero@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (9, 'Lucía', 'Blanco', 'lucia.blanco@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (10, 'Eric', 'García', 'eric.garcia@example.com');
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (1, 'El Infierno', 'Carmen Mola', 2023 , 10);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (2, 'La armadura de la luz', 'Ken Follett', 2023 , 18);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (3, 'El problema final', 'Arturo Pérez-Reverte', 2023 , 8);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (4, 'Holly', 'Stephen King', 2023 , 11);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (5, 'Christine', 'Stephen King', 1983 , 15);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (6, 'Los inocentes', 'María Oruña', 2023 , 12);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (7, 'El hobbit', 'J.R.R. Tolkien', 1937 , 5);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (8, 'Nada es verdad', 'Verónica Raimo', 2022 , 11);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (9, 'La sombra de la rosa', 'Ángela Banzas', 2023 , 7);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (10, 'Este dolor no es mío', 'Mark Wolynn', 2017 , 10);
