INSERT INTO usuarios (id, nombre, apellido, email) VALUES (1, 'Juan', 'Pérez', 'juan.perez@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (2, 'Antonio', 'López', 'antonio.lopez@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (3, 'Marta', 'Torres', 'marta.torres@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (4, 'Alejandro', 'González', 'alejandro.gonzalez@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (5, 'Gonzalo', 'Martínez', 'gonzalo.martinez@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (6, 'Ernesto', 'Ruiz', 'ernesto.ruiz@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (7, 'María', 'Sánchez', 'maria.sanchez@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (8, 'Gerard', 'Romero', 'gerard.romero@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (9, 'Lucía', 'Blanco', 'lucia.blanco@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (10, 'Eric', 'García', 'eric.garcia@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (11, 'Jonatan', 'Gómez', 'jonatan.gomez@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (12, 'Eugenia', 'Serrano', 'eugenia.serrano@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (13, 'Paola', 'Del-Rio', 'paola.delrio@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (14, 'Jose Javier', 'Peral', 'josejavier.peral@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (15, 'Cintia', 'Parejo', 'cintia.parejo@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (16, 'Raquel', 'Valle', 'raquel.valle@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (17, 'Beñat', 'Iglesias', 'beñat.iglesias@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (18, 'Luis', 'Pons', 'luis.pons@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (19, 'Daniel', 'Gómez', 'daniel.gomez@example.com');
INSERT INTO usuarios (id, nombre, apellido, email) VALUES (20, 'Sandra', 'García', 'sandra.garcia@example.com');
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (1, 'El Infierno', 'Carmen Mola', 2023 , 13);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (2, 'La armadura de la luz', 'Ken Follett', 2023 , 18);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (3, 'El problema final', 'Arturo Pérez-Reverte', 2023 , 28);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (4, 'Holly', 'Stephen King', 2023 , 21);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (5, 'Christine', 'Stephen King', 1983 , 15);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (6, 'Los inocentes', 'María Oruña', 2023 , 12);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (7, 'El hobbit', 'J.R.R. Tolkien', 1937 , 15);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (8, 'Nada es verdad', 'Verónica Raimo', 2022 , 11);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (9, 'La sombra de la rosa', 'Ángela Banzas', 2023 , 27);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (10, 'Este dolor no es mío', 'Mark Wolynn', 2017 , 11);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (11, 'El camino de los reyes(El Archivo de las Tormentas 1)', 'Brandon Sanderson', 2010 , 24);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (12, 'Palabras radiantes(El Archivo de las Tormentas 2)', 'Brandon Sanderson', 2014 , 22);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (13, 'Juramentada(El Archivo de las Tormentas 3)', 'Brandon Sanderson', 2017 , 21);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (14, 'Invisible', 'Eloy Moreno', 2018 , 21);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (15, 'Violeta', 'Isabel Allende', 2022 , 19);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (16, 'Más allá del invierno', 'Isabel Allende', 2017 , 20);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (17, 'Cien años de soledad', 'Gabriel García Márquez', 1967, 15);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (18, '1984', 'George Orwell', 1949, 10);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (19, 'El Gran Gatsby', 'F. Scott Fitzgerald', 1925, 12);
INSERT INTO libros (id, nombre, autor, fecha, cantidad) VALUES (20, 'Matar a un ruiseñor', 'Harper Lee', 1960, 18);
